/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_powerline_tags.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_tagpreview.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "alttab.c"
#include "attachx.c"
#include "autostart.c"
#include "cfacts.c"
#include "cmdcustomize.c"
#include "dwmc.c"
#include "ipc.c"
#ifdef VERSION
#include "ipc/IPCClient.c"
#include "ipc/yajl_dumps.c"
#include "ipc/ipc.c"
#include "ipc/util.c"
#endif
#include "moveresize.c"
#include "movestack.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "rotatestack.c"
#include "renamed_scratchpads.c"
#include "setborderpx.c"
#include "sticky.c"
#include "swallow.c"
#include "vanitygaps.c"
#include "xrdb.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_gapplessgrid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

