/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_powerline_tags.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"
#include "bar_layoutmenu.h"

/* Other patches */
#include "alttab.h"
#include "attachx.h"
#include "autostart.h"
#include "cfacts.h"
#include "cmdcustomize.h"
#include "dragmfact.h"
#include "dwmc.h"
#include "ipc.h"
#include "ipc/ipc.h"
#include "ipc/util.h"
#include "moveresize.h"
#include "movestack.h"
#include "pertag.h"
#include "placemouse.h"
#include "restartsig.h"
#include "rotatestack.h"
#include "renamed_scratchpads.h"
#include "seamless_restart.h"
#include "setborderpx.h"
#include "sticky.h"
#include "swallow.h"
#include "vanitygaps.h"
#include "xrdb.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_gapplessgrid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

