/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_anybar.h"
#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_winicon.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "cfacts.h"
#include "cmdcustomize.h"
#include "cyclelayouts.h"
#include "exresize.h"
#include "fullscreen.h"
#include "movestack.h"
#include "pertag.h"
#include "push.h"
#include "restartsig.h"
#include "rotatestack.h"
#include "renamed_scratchpads.h"
#include "seamless_restart.h"
#include "sticky.h"
#include "swallow.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "xrdb.h"
/* Layouts */
#include "layout_gapplessgrid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

